name: Build and Publish john
    
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-john:
    runs-on: alpine:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: ./john/go_install_packages.sh

      - name: Compile
        run: ./john/go_compile.sh
        
      - name: Make zip
        run: ./john/go_make_zip.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            John compiled for Alpine 
            - without CPU acceleration
            - Can run in virtual env
          draft: false
          prerelease: false