name: Build and Publish john
    
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-john:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Compile in docker
        run: cd john && docker build -t alpinejohn .

      - name: Get zip
        run: docker run --rm --entrypoint cat alpinejohn  /john-min.zip > ./john-min.zip
        

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload Latest ./john-min.zip


 