name: Test releases
    
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-releases:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Gen content
        run: echo "Yolo" > ./john-min.zip


      - name: another upload 
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FILE: ./john-min.zip
        run: |
          curl \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: $(file -b --mime-type $FILE)" \
          --data-binary @$FILE \
          "https://uploads.github.com/repos/jossets/AlpineTools/releases/Latest/assets?name=$(basename $FILE)"
        shell: bash
          
          
      - name: Upload release 
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/jossets/AlpineTools/releases/tag/Latest \
          -d '{"tag_name":"Latest","target_commitish":"main","name":"Latest","body":"Alpine tools","draft":false,"prerelease":false}'
        shell: bash



      - name: Get upload url
        run:  |
              upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
              echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
        shell: bash

      # ?name=john-min.zip
      - name: Upload artifact
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./john-min.zip
          asset_name: ./john-min.zip
          asset_content_type: application/gzip



 