name: Test releases
    
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-releases:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Gen content
        run: echo "Yolo" > ./john-min.zip


      # ?name=john-min.zip
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: https://uploads.github.com/repos/AlpineTools/releases/Latest
          asset_path: ./john-min.zip
          asset_name: ./john-min.zip
          asset_content_type: application/gzip



 